name: CI/CD - Build, Push & Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      backend_tag: ${{ steps.build_backend.outputs.tag }}
      frontend_tag: ${{ steps.build_frontend.outputs.tag }}

    steps:
      # 1. Checkout the repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Login to Azure Container Registry
      - name: Login to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} \
            -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # 3. Build & Push Backend
      - name: Build & Push Backend Image
        id: build_backend
        run: |
          TAG=${{ secrets.ACR_LOGIN_SERVER }}/backend:${GITHUB_SHA}
          docker build -t $TAG ./backend
          docker push $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      # 4. Build & Push Frontend
      - name: Build & Push Frontend Image
        id: build_frontend
        run: |
          TAG=${{ secrets.ACR_LOGIN_SERVER }}/frontend:${GITHUB_SHA}
          docker build -t $TAG ./frontend
          docker push $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Setup kubeconfig
      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      # 3. Deploy MongoDB (only first time)
      - name: Apply MongoDB
        run: |
          kubectl apply -f k8s/mongo-pvc.yaml
          kubectl apply -f k8s/mongo-deployment.yaml
          kubectl apply -f k8s/mongo-service.yaml

      # 4. Deploy Backend
      - name: Deploy Backend
        run: |
          sed -i "s|<IMAGE_TAG>|${{ needs.build-and-push.outputs.backend_tag }}|g" k8s/backend-deployment.yaml
          echo "✅ Final backend-deployment.yaml content (checking image line):"
          grep "image:" k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml

      # 5. Deploy Frontend
      - name: Deploy Frontend
        run: |
          sed -i "s|<IMAGE_TAG>|${{ needs.build-and-push.outputs.frontend_tag }}|g" k8s/frontend-deployment.yaml
          echo "✅ Final frontend-deployment.yaml content (checking image line):"
          grep "image:" k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml

      # 6. Verify
      - name: Get Pods & Services
        run: |
          kubectl get pods
          kubectl get svc
