name: CI/CD - Full Stack App

on:
  push:
    branches:
      - main

env:
  ACR_NAME: democontainerregistry123
  ACR_LOGIN_SERVER: democontainerregistry123.azurecr.io
  K8S_NAMESPACE: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Azure Login
      - name: Azure CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Azure ACR Login
      - name: Azure Container Registry Login
        run: az acr login --name $ACR_NAME

      # 4️⃣ Build & Push Backend Image
      - name: Build & Push Backend
        run: |
          BACKEND_TAG=$(date +%Y%m%d%H%M%S)
          docker build -t $ACR_LOGIN_SERVER/backend:$BACKEND_TAG ./backend
          docker push $ACR_LOGIN_SERVER/backend:$BACKEND_TAG
          echo "BACKEND_TAG=$BACKEND_TAG" >> $GITHUB_ENV

      # 5️⃣ Build & Push Frontend Image
      - name: Build & Push Frontend
        run: |
          FRONTEND_TAG=$(date +%Y%m%d%H%M%S)
          docker build -t $ACR_LOGIN_SERVER/frontend:$FRONTEND_TAG ./frontend
          docker push $ACR_LOGIN_SERVER/frontend:$FRONTEND_TAG
          echo "FRONTEND_TAG=$FRONTEND_TAG" >> $GITHUB_ENV

      # 6️⃣ Build & Push Mongo Image (if custom)
      - name: Build & Push Mongo
        run: |
          MONGO_TAG=$(date +%Y%m%d%H%M%S)
          docker build -t $ACR_LOGIN_SERVER/mongo:$MONGO_TAG ./mongo
          docker push $ACR_LOGIN_SERVER/mongo:$MONGO_TAG
          echo "MONGO_TAG=$MONGO_TAG" >> $GITHUB_ENV

      # 7️⃣ Setup kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      # 8️⃣ Get AKS Credentials
      - name: AKS login
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AKS_RG }} \
            --name ${{ secrets.AKS_NAME }} \
            --overwrite-existing

      # 9️⃣ Update Kubernetes Manifests
      - name: Update Kubernetes YAMLs
        run: |
          sed -i "s|<BACKEND_IMAGE>|$ACR_LOGIN_SERVER/backend:${BACKEND_TAG}|g" k8s/backend-deployment.yaml
          sed -i "s|<FRONTEND_IMAGE>|$ACR_LOGIN_SERVER/frontend:${FRONTEND_TAG}|g" k8s/frontend-deployment.yaml
          sed -i "s|<MONGO_IMAGE>|$ACR_LOGIN_SERVER/mongo:${MONGO_TAG}|g" k8s/mongo-deployment.yaml

      # 🔟 Deploy to AKS
      - name: Apply Manifests
        run: |
          kubectl apply -f k8s/mongo-deployment.yaml -n $K8S_NAMESPACE
          kubectl apply -f k8s/mongo-service.yaml -n $K8S_NAMESPACE
          kubectl apply -f k8s/backend-deployment.yaml -n $K8S_NAMESPACE
          kubectl apply -f k8s/backend-service.yaml -n $K8S_NAMESPACE
          kubectl apply -f k8s/frontend-deployment.yaml -n $K8S_NAMESPACE
          kubectl apply -f k8s/frontend-service.yaml -n $K8S_NAMESPACE
